### ISSUE TITLE
phylo: `clean` rule removes the USVI data

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/zika#37]
Running the `clean` rule in the phylogenetic workflow removes the USVI data that was added in https://github.com/nextstrain/zika/pull/31

So if you run `clean` then try to run the workflow, it results in an error:

```
$ nextstrain build phylogenetic/ clean
...
$ nextstrain build phylogenetic/ 
Building DAG of jobs...
MissingInputException in rule append_usvi in file /nextstrain/build/rules/merge_sequences_usvi.smk, line 24:
Missing input files for rule append_usvi:
    output: data/sequences_all.fasta, data/metadata_all.tsv
    affected files:
        data/metadata_usvi.tsv
        data/sequences_usvi.fasta
```

## Possible solution

I think easiest to just move the USVI data to a different directory, e.g. `usvi_data`, so that it does not get removed with the workflow data.

**Comment by j23414** [comment]
Other options include:

* moving USVI data back to being downloading from a URL (I think we didn't go this route because we wanted the README documentation?)
* more specifically cleaning up `data/metadata.tsv`, `data/sequences.fasta`, `data/metadata_all.tsv`, and `data/sequences_all.fasta` at https://github.com/nextstrain/zika/blob/c710ca181f23444553bceb46cb00ced9db4eece8/phylogenetic/Snakefile#L22 which would bypass creating another directory
* creating a `local_data` folder instead where users can spike in any of their own sequences and records
