### ISSUE TITLE
Pass credentials as environment variables

### ISSUE THREAD

**Issue by trvrb** [nextstrain/zika#4]
Currently, sensitive credentials are intended to be added to the file `config_local.yaml`. I don't like this approach. First off, it's intended to add other overrides to the `config_local.yaml`. This file should _never_ risk being committed to GitHub and wrapping these together increases this risk greatly. 

The pattern I'm used to here is to store credentials as environment variables. This is the pattern encouraged by services like Heroku and Travis CI. It's also hugely convenient for AWS EC2. Rather than looking in the `config_local.yaml`, I'd recommend that the build use environment variables `RETHINK_HOST` and `RETHINK_AUTH_KEY`.

I got this working easily for a local `snakemake` call. However, I stumbled when I tried to make this work with the containerized `nextstrain build` call.

**Comment by tsibley** [comment]
I actually was using environment variables first, and then moved to using the local config, and recently had been considering switching back because, among other things, the creds are visible in `ps` output in the current state of things (not an issue locally, more of one if we're running on a shared host like rhino).

I know how to make this possible easily, and will push a branch to do so.

FWIW, `config_local.yaml` is in `.gitignore`, so it's hard to commit it.

**Comment by tsibley** [comment]
I pushed a draft proposal for this on `wip/envdir`: https://github.com/nextstrain/zika/commit/2d1470720a9c41e8861e37557e9409ee41675d07

Thoughts before I take it further?

**Comment by trvrb** [comment]
I'm a bit confused on why `envdir` with files are necessary vs just looking at environment variables with `os.environ`.

**Comment by tsibley** [comment]
Hmm, you're talking about having the Snakefile look at `os.environ` and explicitly pass the expected environment values into fauna in the `download` rule?  That would work (but be unnecessary) for local builds, but it would not work for containerized builds. Something needs to pass the environment from outside the container into the container.  In the case of an envdir, it's reading the shared filesystem. There are other solutions like some `nextstrain build` option that passes values into the container, but I think that starts to get ugly, as you have to specify it everytime.

I would prefer to have a single system for defining environment variables supported by all kinds of builds (local, containerized, etc) rather than having a situation where everyone uses some slightly different way of keeping them around. "Put the values into these files in `envdir/`" is clearer to me than "Throw them in a local shell script and source it, or export them interactively in your shell, or run using `env`, or …". The envdir concept is used fairly commonly and lets us standardize environment config across builds.

Does that make sense?

---

As a side note, I was tempted this afternoon to look into writing a feature patch for Snakemake to accept something like:

```
envdir: "path/to/envdir/"
```

and a corresponding `--envdir` option to `snakemake`.  (It could also be `envfile:`, though I think envdirs are nicer than envfiles for several reasons.)
